services:
  - type: web
    name: customer-segmentation-dashboard
    runtime: node
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: customer-db
          property: connectionString
    autoDeploy: false

databases:
  - name: customer-db
    databaseName: customer_segmentation
    user: dashboard_user
    plan: free